"what is your first name?"
first_name = "Carla"
"What's your last name? "
last_name = "Herran"
"What city are you from? "
city = "Mexico"
"What state or providence are you from? "
state = "cdmx"
puts "Your name is #{first_name} #{last_name} and you're from #{city}, #{state}"